dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - bin/parallel-lint --exclude bin --exclude vendor --exclude web .
  - bin/phpunit

jobs:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.1
      env: Other lints
      script:
        - bin/xmllint --pattern "*.xlf*,svg" Resources
    - php: 7.1
      env: Codestyle
      script:
        - bin/phpcs

    - stage: deploy
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script: >
        if [ -n "$TRAVIS_TAG" ]; then
          echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

          if [ $? -eq 0 ]; then
            TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
            TAG_MESSAGE="${TAG_ANNOTATION#* }"

            git reset --hard
            git clean -xfd

            composer global require helhum/ter-client dev-master

            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload $(composer config extra.typo3/cms.extension-key) . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
        fi;

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
