dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer require typo3/cms="$TYPO3_VERSION" --update-with-dependencies

script:
  - composer test

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - &lint
      stage: lint
      php: 7.0
      env: PHP lint
      install:
        - composer install
      script:
        - composer lint:php
    - <<: *lint
      php: 7.1
    - <<: *lint
      php: 7.1
      env: XML lint
      script:
        - composer lint:xml

    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^7.6
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^7.6
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7

    - stage: test
      php: 7.1
      env: Codestyle
      install:
        - composer install
      script:
        - composer lint:style

    - stage: deploy
      if: tag IS present
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script: |
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"

        git reset --hard
        git clean -xfd

        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
        composer global require helhum/ter-client dev-master

        echo "Uploading release ${TRAVIS_TAG} to TER"
        ter-client upload $(composer config extra.typo3/cms.extension-key) . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
